// <auto-generated />
using System;
using ELearnGamePlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ELearnGamePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416144422_AddFolderProjectsFlow")]
    partial class AddFolderProjectsFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageMapJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage_map");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<int?>("FolderProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("folder_project_id");

                    b.Property<int>("FolderSourceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("folder_source_order");

                    b.Property<bool>("IncludeInFolderSlides")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_folder_slides");

                    b.Property<string>("KeyPointsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("key_points");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("MainTopicsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("main_topics");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FolderProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("FolderProjectId", "FolderSourceOrder");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.FolderProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UploadedBy");

                    b.ToTable("folder_projects");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("GameType")
                        .HasColumnType("integer")
                        .HasColumnName("game_type");

                    b.Property<string>("QuestionIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("question_ids");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("game_sessions");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("VerifierIssuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("verifier_issues");

                    b.Property<int?>("VerifierScore")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_score");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "QuestionType");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int?>("FolderProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("folder_project_id");

                    b.Property<string>("OutlineJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("outline");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subtitle");

                    b.Property<string>("ThemeKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("theme_key");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FolderProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("DocumentId", "CreatedAt");

                    b.HasIndex("FolderProjectId", "CreatedAt");

                    b.ToTable("slide_decks");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentTone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("accent_tone");

                    b.Property<string>("BodyJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EditorStateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("editor_state");

                    b.Property<string>("Goal")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("goal");

                    b.Property<string>("Heading")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("heading");

                    b.Property<string>("ImageCandidatesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_candidates");

                    b.Property<string>("ImagePlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_plan");

                    b.Property<string>("SelectedImageKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("selected_image_key");

                    b.Property<int>("SlideDeckId")
                        .HasColumnType("integer")
                        .HasColumnName("slide_deck_id");

                    b.Property<int>("SlideIndex")
                        .HasColumnType("integer")
                        .HasColumnName("slide_index");

                    b.Property<int>("SlideType")
                        .HasColumnType("integer")
                        .HasColumnName("slide_type");

                    b.Property<string>("SpeakerNotes")
                        .HasColumnType("text")
                        .HasColumnName("speaker_notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subheading")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subheading");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifierIssuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("verifier_issues");

                    b.Property<int?>("VerifierScore")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_score");

                    b.HasKey("Id");

                    b.HasIndex("SlideDeckId");

                    b.HasIndex("Status");

                    b.HasIndex("SlideDeckId", "SlideIndex");

                    b.ToTable("slide_items");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Document", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.FolderProject", "FolderProject")
                        .WithMany("Documents")
                        .HasForeignKey("FolderProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FolderProject");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.GameSession", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("GameSessions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Question", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("Questions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideDeck", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("SlideDecks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ELearnGamePlatform.Core.Entities.FolderProject", "FolderProject")
                        .WithMany("SlideDecks")
                        .HasForeignKey("FolderProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");

                    b.Navigation("FolderProject");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideItem", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.SlideDeck", "SlideDeck")
                        .WithMany("Items")
                        .HasForeignKey("SlideDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlideDeck");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Document", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Questions");

                    b.Navigation("SlideDecks");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.FolderProject", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SlideDecks");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideDeck", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
