// <auto-generated />
using System;
using ELearnGamePlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ELearnGamePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608002005_AddClassroomAssignments")]
    partial class AddClassroomAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.AnalyticsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties_json");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SessionId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("session_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ReceivedAt");

                    b.ToTable("analytics_events");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.ToTable("app_users");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptLimit")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_limit");

                    b.Property<int>("ClassroomWorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_workspace_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("question_set_id");

                    b.Property<bool>("ShowAnswerAfterSubmit")
                        .HasColumnType("boolean")
                        .HasColumnName("show_answer_after_submit");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_options");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_questions");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomWorkspaceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QuestionSetId");

                    b.HasIndex("Status");

                    b.ToTable("classroom_assignments");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignmentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<decimal>("PointEarned")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("point_earned");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("selected_answer");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_seconds");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("classroom_assignment_answers");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignmentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<int>("ClassroomAssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_assignment_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<decimal>("PercentScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percent_score");

                    b.Property<decimal>("RawScore")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("raw_score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("ClassroomAssignmentId", "UserId");

                    b.ToTable("classroom_assignment_attempts");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomJoinCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomWorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_workspace_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ClassroomWorkspaceId", "IsActive");

                    b.ToTable("classroom_join_codes");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomWorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_workspace_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("ClassroomWorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("classroom_members");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomQuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomWorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_workspace_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomWorkspaceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DocumentId");

                    b.ToTable("classroom_question_sets");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomQuestionSetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomQuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_question_set_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<double>("PointWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("point_weight");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("SectionCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("section_code");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ClassroomQuestionSetId", "QuestionId")
                        .IsUnique();

                    b.ToTable("classroom_question_set_items");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("classroom_workspaces");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageMapJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage_map");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<int?>("FolderProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("folder_project_id");

                    b.Property<int>("FolderSourceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("folder_source_order");

                    b.Property<bool>("IncludeInFolderSlides")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_folder_slides");

                    b.Property<string>("KeyPointsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("key_points");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("MainTopicsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("main_topics");

                    b.Property<string>("ProcessedMetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("processed_metadata");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FolderProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("FolderProjectId", "FolderSourceOrder");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.DocumentUnderstandingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CombinedText")
                        .HasColumnType("text")
                        .HasColumnName("combined_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DocumentConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("document_confidence");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FailureReasonsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("failure_reasons");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_review");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DocumentId", "CreatedAt");

                    b.ToTable("document_understanding_runs");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.FolderProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UploadedBy");

                    b.ToTable("folder_projects");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("GameType")
                        .HasColumnType("integer")
                        .HasColumnName("game_type");

                    b.Property<string>("QuestionIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("question_ids");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("game_sessions");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Confidence")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("selected_answer");

                    b.Property<int?>("TestResultId")
                        .HasColumnType("integer")
                        .HasColumnName("test_result_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestResultId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DocumentId", "CreatedAt");

                    b.HasIndex("UserId", "DocumentId", "QuestionId");

                    b.ToTable("learning_attempts");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("best_streak");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<double>("MasteryScore")
                        .HasColumnType("double precision")
                        .HasColumnName("mastery_score");

                    b.Property<double>("MemoryScore")
                        .HasColumnType("double precision")
                        .HasColumnName("memory_score");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_count");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DocumentId");

                    b.HasIndex("UserId", "DocumentId", "QuestionId")
                        .IsUnique();

                    b.ToTable("learning_progresses");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("QuestionIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("question_ids");

                    b.Property<string>("ResultSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_snapshot");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_session_id");

                    b.Property<int>("TestType")
                        .HasColumnType("integer")
                        .HasColumnName("test_type");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_count");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("TestSessionId")
                        .IsUnique();

                    b.HasIndex("TestType");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DocumentId");

                    b.HasIndex("UserId", "DocumentId", "SubmittedAt");

                    b.ToTable("learning_test_results");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<double?>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<int?>("SourceDraftId")
                        .HasColumnType("integer")
                        .HasColumnName("source_draft_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("VerifierIssuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("verifier_issues");

                    b.Property<int?>("VerifierScore")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_score");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("SourceDraftId")
                        .IsUnique()
                        .HasFilter("source_draft_id IS NOT NULL");

                    b.HasIndex("DocumentId", "QuestionType");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AnswerScore")
                        .HasColumnType("double precision")
                        .HasColumnName("answer_score");

                    b.Property<double>("ClarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("clarity_score");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("DraftKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("draft_kind");

                    b.Property<double>("DuplicateScore")
                        .HasColumnType("double precision")
                        .HasColumnName("duplicate_score");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int>("GenerationRunId")
                        .HasColumnType("integer")
                        .HasColumnName("generation_run_id");

                    b.Property<double>("GroundingScore")
                        .HasColumnType("double precision")
                        .HasColumnName("grounding_score");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("LearningObjective")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("learning_objective");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<int?>("ParentDraftId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_draft_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("question_type");

                    b.Property<int>("RepairCount")
                        .HasColumnType("integer")
                        .HasColumnName("repair_count");

                    b.Property<string>("SourceEvidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_evidence");

                    b.Property<int?>("SourceUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("source_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("StemHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stem_hash");

                    b.Property<string>("TopicTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic_tag");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentDraftId");

                    b.HasIndex("SourceUnitId");

                    b.HasIndex("StemHash");

                    b.HasIndex("DocumentId", "Status");

                    b.HasIndex("GenerationRunId", "Status");

                    b.HasIndex("TopicTag", "Difficulty");

                    b.ToTable("question_drafts");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionGenerationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BorderlineCount")
                        .HasColumnType("integer")
                        .HasColumnName("borderline_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FailureStatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("failure_stats");

                    b.Property<int>("GeneratedDraftCount")
                        .HasColumnType("integer")
                        .HasColumnName("generated_draft_count");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer")
                        .HasColumnName("imported_count");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("mode");

                    b.Property<string>("ModelProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("model_profile");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("integer")
                        .HasColumnName("quarantined_count");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_count");

                    b.Property<string>("RequestedDifficultiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requested_difficulties");

                    b.Property<string>("RequestedQuestionTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requested_question_types");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<int>("TargetDraftCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_draft_count");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("VerifiedDraftCount")
                        .HasColumnType("integer")
                        .HasColumnName("verified_draft_count");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("DocumentId", "CreatedAt");

                    b.ToTable("question_generation_runs");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionReviewEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("QuestionDraftId")
                        .HasColumnType("integer")
                        .HasColumnName("question_draft_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("QuestionDraftId");

                    b.HasIndex("QuestionDraftId", "CreatedAt");

                    b.ToTable("question_review_events");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionSourceUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<int?>("GenerationRunId")
                        .HasColumnType("integer")
                        .HasColumnName("generation_run_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_hash");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.Property<string>("TopicTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic_tag");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id");

                    b.HasIndex("GenerationRunId");

                    b.HasIndex("SourceHash");

                    b.HasIndex("DocumentId", "TopicTag");

                    b.ToTable("question_source_units");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int?>("FolderProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("folder_project_id");

                    b.Property<string>("OutlineJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("outline");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subtitle");

                    b.Property<string>("ThemeKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("theme_key");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FolderProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("DocumentId", "CreatedAt");

                    b.HasIndex("FolderProjectId", "CreatedAt");

                    b.ToTable("slide_decks");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentTone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("accent_tone");

                    b.Property<string>("BodyJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EditorStateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("editor_state");

                    b.Property<string>("EvidenceDebugJson")
                        .HasColumnType("text")
                        .HasColumnName("evidence_debug");

                    b.Property<string>("EvidenceFromText")
                        .HasColumnType("text")
                        .HasColumnName("evidence_from_text");

                    b.Property<string>("Goal")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("goal");

                    b.Property<string>("Heading")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("heading");

                    b.Property<string>("ImageCandidatesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_candidates");

                    b.Property<string>("ImagePlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_plan");

                    b.Property<string>("KeyMessage")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("key_message");

                    b.Property<string>("SelectedImageKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("selected_image_key");

                    b.Property<int>("SlideDeckId")
                        .HasColumnType("integer")
                        .HasColumnName("slide_deck_id");

                    b.Property<int>("SlideIndex")
                        .HasColumnType("integer")
                        .HasColumnName("slide_index");

                    b.Property<int>("SlideType")
                        .HasColumnType("integer")
                        .HasColumnName("slide_type");

                    b.Property<string>("SpeakerNotes")
                        .HasColumnType("text")
                        .HasColumnName("speaker_notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subheading")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subheading");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifierIssuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("verifier_issues");

                    b.Property<int?>("VerifierScore")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_score");

                    b.HasKey("Id");

                    b.HasIndex("SlideDeckId");

                    b.HasIndex("Status");

                    b.HasIndex("SlideDeckId", "SlideIndex");

                    b.ToTable("slide_items");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignment", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", "ClassroomWorkspace")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassroomWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomQuestionSet", "QuestionSet")
                        .WithMany("Assignments")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassroomWorkspace");

                    b.Navigation("CreatedByUser");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignmentAnswer", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomAssignmentAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.Question", "Question")
                        .WithMany("ClassroomAssignmentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignmentAttempt", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomAssignment", "Assignment")
                        .WithMany("Attempts")
                        .HasForeignKey("ClassroomAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomJoinCode", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", "ClassroomWorkspace")
                        .WithMany("JoinCodes")
                        .HasForeignKey("ClassroomWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassroomWorkspace");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomMember", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", "ClassroomWorkspace")
                        .WithMany("Members")
                        .HasForeignKey("ClassroomWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassroomWorkspace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomQuestionSet", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", "ClassroomWorkspace")
                        .WithMany("QuestionSets")
                        .HasForeignKey("ClassroomWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("ClassroomQuestionSets")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClassroomWorkspace");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomQuestionSetItem", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.ClassroomQuestionSet", "ClassroomQuestionSet")
                        .WithMany("Items")
                        .HasForeignKey("ClassroomQuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.Question", "Question")
                        .WithMany("ClassroomQuestionSetItems")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassroomQuestionSet");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Document", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.FolderProject", "FolderProject")
                        .WithMany("Documents")
                        .HasForeignKey("FolderProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FolderProject");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.DocumentUnderstandingRun", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("UnderstandingRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.GameSession", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("GameSessions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningAttempt", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("LearningAttempts")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.Question", "Question")
                        .WithMany("LearningAttempts")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.LearningTestResult", "TestResult")
                        .WithMany("Attempts")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("Question");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningProgress", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.Question", "Question")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningTestResult", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("LearningTestResults")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Question", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("Questions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionDraft", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("QuestionDrafts")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.QuestionGenerationRun", "GenerationRun")
                        .WithMany("Drafts")
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.QuestionDraft", "ParentDraft")
                        .WithMany("Variants")
                        .HasForeignKey("ParentDraftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ELearnGamePlatform.Core.Entities.QuestionSourceUnit", "SourceUnit")
                        .WithMany("Drafts")
                        .HasForeignKey("SourceUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("GenerationRun");

                    b.Navigation("ParentDraft");

                    b.Navigation("SourceUnit");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionGenerationRun", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("QuestionGenerationRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionReviewEvent", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.QuestionDraft", "QuestionDraft")
                        .WithMany("ReviewEvents")
                        .HasForeignKey("QuestionDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionDraft");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionSourceUnit", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("QuestionSourceUnits")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELearnGamePlatform.Core.Entities.QuestionGenerationRun", "GenerationRun")
                        .WithMany("SourceUnits")
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");

                    b.Navigation("GenerationRun");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideDeck", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.Document", "Document")
                        .WithMany("SlideDecks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ELearnGamePlatform.Core.Entities.FolderProject", "FolderProject")
                        .WithMany("SlideDecks")
                        .HasForeignKey("FolderProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");

                    b.Navigation("FolderProject");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideItem", b =>
                {
                    b.HasOne("ELearnGamePlatform.Core.Entities.SlideDeck", "SlideDeck")
                        .WithMany("Items")
                        .HasForeignKey("SlideDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlideDeck");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignment", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomAssignmentAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomQuestionSet", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.ClassroomWorkspace", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("JoinCodes");

                    b.Navigation("Members");

                    b.Navigation("QuestionSets");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Document", b =>
                {
                    b.Navigation("ClassroomQuestionSets");

                    b.Navigation("GameSessions");

                    b.Navigation("LearningAttempts");

                    b.Navigation("LearningProgresses");

                    b.Navigation("LearningTestResults");

                    b.Navigation("QuestionDrafts");

                    b.Navigation("QuestionGenerationRuns");

                    b.Navigation("QuestionSourceUnits");

                    b.Navigation("Questions");

                    b.Navigation("SlideDecks");

                    b.Navigation("UnderstandingRuns");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.FolderProject", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SlideDecks");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.LearningTestResult", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.Question", b =>
                {
                    b.Navigation("ClassroomAssignmentAnswers");

                    b.Navigation("ClassroomQuestionSetItems");

                    b.Navigation("LearningAttempts");

                    b.Navigation("LearningProgresses");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionDraft", b =>
                {
                    b.Navigation("ReviewEvents");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionGenerationRun", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("SourceUnits");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.QuestionSourceUnit", b =>
                {
                    b.Navigation("Drafts");
                });

            modelBuilder.Entity("ELearnGamePlatform.Core.Entities.SlideDeck", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
