<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ELearnGamePlatform.Core\ELearnGamePlatform.Core.csproj" />
    <ProjectReference Include="..\..\src\ELearnGamePlatform.Services\ELearnGamePlatform.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\ELearnGamePlatform.API\tessdata\**\*">
      <Link>tessdata\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
